import type { Integration } from "../base.js";
import type { PullRequestRef } from "../github/types.js";
import { createLogger, type Logger } from "../../logger.js";

export interface SlackIntegrationOptions {
  /** Slack bot user OAuth token (xoxb-...). */
  token: string;
  /** Target channel id or name. */
  channel: string;
  /** Optional override for the Slack Web API base URL (used in tests). */
  apiBaseUrl?: string;
  /** Optional logger; defaults to a pino logger named "slack". */
  logger?: Logger;
  /** Optional fetch implementation; defaults to global fetch. */
  fetchImpl?: typeof fetch;
}

export type PullRequestNotificationKind = "opened" | "updated";

export interface PullRequestNotification {
  kind: PullRequestNotificationKind;
  pr: PullRequestRef;
  /** PR title. */
  title: string;
  /** PR HTML url. */
  url: string;
  /** Originating Linear ticket identifier (e.g. "DEN-2305"). */
  ticketId: string;
  /** Optional Linear ticket url. */
  ticketUrl?: string;
}

const DEFAULT_API_BASE_URL = "https://slack.com/api";

/**
 * Posts notifications to Slack via chat.postMessage. The channel and bot token are
 * supplied by the operator via env vars (see manager/config.ts). Per-tenant channel
 * configuration is future work — for now there is a single workspace-wide channel.
 */
export class SlackIntegration implements Integration {
  readonly name = "slack";
  private readonly token: string;
  private readonly channel: string;
  private readonly apiBaseUrl: string;
  private readonly logger: Logger;
  private readonly fetchImpl: typeof fetch;

  constructor(options: SlackIntegrationOptions) {
    if (!options.token) {
      throw new Error("SlackIntegration requires a bot token");
    }
    if (!options.channel) {
      throw new Error("SlackIntegration requires a target channel");
    }
    this.token = options.token;
    this.channel = options.channel;
    this.apiBaseUrl = options.apiBaseUrl ?? DEFAULT_API_BASE_URL;
    this.logger = options.logger ?? createLogger({ level: "info", name: "slack" });
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  /**
   * Post a "PR opened" or "PR updated" notification to the configured channel.
   * Failures are logged but never thrown — Slack outages must not break the
   * worker's commit/push flow, which has already succeeded by the time we get here.
   */
  async notifyPullRequest(notification: PullRequestNotification): Promise<void> {
    const text = formatNotificationText(notification);
    try {
      const response = await this.fetchImpl(`${this.apiBaseUrl}/chat.postMessage`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json; charset=utf-8",
          Authorization: `Bearer ${this.token}`,
        },
        body: JSON.stringify({
          channel: this.channel,
          text,
          unfurl_links: false,
          unfurl_media: false,
        }),
      });
      if (!response.ok) {
        this.logger.error(
          { status: response.status, statusText: response.statusText, channel: this.channel },
          "slack chat.postMessage HTTP error",
        );
        return;
      }
      const body = (await response.json()) as { ok: boolean; error?: string };
      if (!body.ok) {
        this.logger.error({ error: body.error, channel: this.channel }, "slack chat.postMessage returned ok=false");
      }
    } catch (err) {
      this.logger.error({ err, channel: this.channel }, "slack chat.postMessage threw");
    }
  }
}

/**
 * Escape characters that have special meaning in Slack mrkdwn so that
 * untrusted text (e.g. PR titles or ticket ids generated by an AI agent)
 * can't smuggle in `<url|label>` links or otherwise distort the message.
 * See https://api.slack.com/reference/surfaces/formatting#escaping.
 */
function escapeSlackMrkdwn(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function formatNotificationText(notification: PullRequestNotification): string {
  const { kind, pr, title, url, ticketId, ticketUrl } = notification;
  const verb = kind === "opened" ? "opened" : "updated";
  const icon = kind === "opened" ? ":rocket:" : ":arrows_counterclockwise:";
  const safeTitle = escapeSlackMrkdwn(title);
  const safeTicketId = escapeSlackMrkdwn(ticketId);
  const prLink = `<${url}|${escapeSlackMrkdwn(pr.owner)}/${escapeSlackMrkdwn(pr.repo)}#${pr.number}>`;
  const ticketLabel = ticketUrl ? `<${ticketUrl}|${safeTicketId}>` : safeTicketId;
  return `${icon} *PR ${verb}* ${prLink} — ${safeTitle} (ticket: ${ticketLabel})`;
}
